services:
  - type: web
    name: lark-mcp-telegram-server-v2
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    plan: starter
    envVars:
      - key: PORT
        value: 10000
      - key: RENDER
        value: production